Repository DaeChamSa/with-the-developer, pull requests merged in 2024-09, with the labels that each got.

#5 [Chore/setting] yml 변경 (ddl-auto create 추가)
  README.md
  back-end/with-the-developer/src/main/resources/application.yml
Labels: :1234: chore

#9 Feat/user 사용자 회원가입, 로그인, 로그아웃 추가 & chore: 병합 오류 해결, 코멘트 수정
  back-end/with-the-developer/.gitignore
  back-end/with-the-developer/build.gradle
  back-end/with-the-developer/src/main/java/com/developer/command/controller/UserController.java
  back-end/with-the-developer/src/main/java/com/developer/command/controller/test.md
  back-end/with-the-developer/src/main/java/com/developer/command/dto/LoginUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/command/dto/RegisterUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/command/dto/test.md
  back-end/with-the-developer/src/main/java/com/developer/command/entity/Email.java
  back-end/with-the-developer/src/main/java/com/developer/command/entity/User.java
  back-end/with-the-developer/src/main/java/com/developer/command/entity/test.md
  back-end/with-the-developer/src/main/java/com/developer/command/repository/EmailRepository.java
  back-end/with-the-developer/src/main/java/com/developer/command/repository/UserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/command/repository/test.md
  back-end/with-the-developer/src/main/java/com/developer/command/service/EmailService.java
  back-end/with-the-developer/src/main/java/com/developer/command/service/UserService.java
  back-end/with-the-developer/src/main/java/com/developer/command/service/test.md
  back-end/with-the-developer/src/main/java/com/developer/common/exception/CustomException.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorResponse.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/GlobalExceptionHandler.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/test.md
  back-end/with-the-developer/src/main/java/com/developer/config/BeanConfig.java
  back-end/with-the-developer/src/main/java/com/developer/config/test.md
  back-end/with-the-developer/src/main/java/com/developer/query/mapper/UserMapper.java
  back-end/with-the-developer/src/main/java/com/developer/query/mapper/test.md
  back-end/with-the-developer/src/main/resources/application.yml
Labels: :new: feat, :memo: docs, :1234: chore

#10 [chore] main에서 develop으로 기본브랜치 변경
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  README.md
  back-end/with-the-developer/.gitignore
  back-end/with-the-developer/build.gradle
  back-end/with-the-developer/gradle/wrapper/gradle-wrapper.jar
  back-end/with-the-developer/gradle/wrapper/gradle-wrapper.properties
  back-end/with-the-developer/gradlew
  back-end/with-the-developer/gradlew.bat
  back-end/with-the-developer/settings.gradle
  back-end/with-the-developer/src/main/java/com/developer/WithTheDeveloperApplication.java
  back-end/with-the-developer/src/main/java/com/developer/command/controller/UserController.java
  back-end/with-the-developer/src/main/java/com/developer/command/dto/LoginUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/command/dto/RegisterUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/command/entity/Email.java
  back-end/with-the-developer/src/main/java/com/developer/command/entity/User.java
  back-end/with-the-developer/src/main/java/com/developer/command/repository/EmailRepository.java
  back-end/with-the-developer/src/main/java/com/developer/command/repository/UserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/command/service/EmailService.java
  back-end/with-the-developer/src/main/java/com/developer/command/service/UserService.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/CustomException.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorResponse.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/GlobalExceptionHandler.java
  back-end/with-the-developer/src/main/java/com/developer/config/BeanConfig.java
  back-end/with-the-developer/src/main/java/com/developer/query/controller/test.md
  back-end/with-the-developer/src/main/java/com/developer/query/dto/test.md
  back-end/with-the-developer/src/main/java/com/developer/query/mapper/UserMapper.java
  back-end/with-the-developer/src/main/java/com/developer/query/service/test.md
  back-end/with-the-developer/src/main/resources/application.yml
  back-end/with-the-developer/src/test/java/com/developer/WithTheDeveloperApplicationTests.java
  front-end/test.md
Labels: :1234: chore

#13 [chore/ymlConfig] #12 yml에 API-KEY값 적용, ddl-auto none으로 변경, .gitignore 파일 레벨 with-the-developer로 이동
  .gitignore
  back-end/with-the-developer/src/main/resources/application.yml
Labels: :1234: chore

#15 [feat/user-entity] #14 회원 기초 CRUD 완성, unique값 중복검증 로직 추가, DTO 추가
  back-end/with-the-developer/src/main/java/com/developer/command/controller/UserController.java
  back-end/with-the-developer/src/main/java/com/developer/command/dto/ResponseUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/command/dto/UpdateUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/command/entity/User.java
  back-end/with-the-developer/src/main/java/com/developer/command/repository/UserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/command/service/UserService.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/config/BeanConfig.java
Labels: :new: feat, :1234: chore

#21 chore: #20 폴더 구조 도메인별로 변경
  back-end/with-the-developer/src/main/java/com/developer/config/BeanConfig.java
  back-end/with-the-developer/src/main/java/com/developer/query/mapper/UserMapper.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/controller/UserController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/LoginUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/RegisterUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/ResponseUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/UpdateUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/Email.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/User.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/repository/EmailRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/repository/UserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/service/EmailService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/service/UserService.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/controller/test.md
  back-end/with-the-developer/src/main/java/com/developer/user/query/dto/test.md
  back-end/with-the-developer/src/main/java/com/developer/user/query/mapper/UserMapper.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/service/test.md
Labels: :1234: chore

#25 refactor: #24 user파트 조회 mybatis로 변경 및 mybatisConfig 생성
  back-end/with-the-developer/src/main/java/com/developer/config/MybatisConfig.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/ResponseUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/SendEmailDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/SessionSaveDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/Email.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/User.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/service/EmailCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/service/UserCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/controller/UserQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/controller/test.md
  back-end/with-the-developer/src/main/java/com/developer/user/query/dto/CheckCodeDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/dto/test.md
  back-end/with-the-developer/src/main/java/com/developer/user/query/mapper/EmailMapper.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/mapper/UserMapper.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/service/EmailQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/service/UserQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/service/test.md
  back-end/with-the-developer/src/main/resources/application.yml
  back-end/with-the-developer/src/main/resources/com/developer/user/query/mapper/emailMapper.xml
  back-end/with-the-developer/src/main/resources/com/developer/user/query/mapper/userMapper.xml
Labels: :new: feat, :recycle: refactor

#27 chore: #26 mybatisConfig 설정 삭제 이후 yml에 추가
  back-end/with-the-developer/src/main/java/com/developer/config/BeanConfig.java
  back-end/with-the-developer/src/main/java/com/developer/config/MybatisConfig.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/User.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/UserStatus.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/controller/UserQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/dto/FindIdDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/dto/ResponseUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/mapper/UserMapper.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/service/UserQueryService.java
  back-end/with-the-developer/src/main/resources/application.yml
  back-end/with-the-developer/src/main/resources/mappers/user/emailMapper.xml
  back-end/with-the-developer/src/main/resources/mappers/user/userMapper.xml
Labels: :1234: chore, :recycle: refactor

#31 [Feat/teampost] #16 팀 모집 게시글 기초 CRUD 및 이미지 저장 기능 일부 구현
  back-end/with-the-developer/build.gradle
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/util/FileUploadUtils.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/controller/TeamPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/dto/TeamPostDeleteDTO.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/dto/TeamPostRegistDTO.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/dto/TeamPostUpdateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/entity/TeamPost.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/repository/TeamPostRepository.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/service/TeamPostCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/query/controller/TeamPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/query/dto/TeamPostDTO.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/query/dto/TeamPostListDTO.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/query/dto/UserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/query/mapper/TeamPostMapper.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/query/service/TeamPostQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/User.java
  back-end/with-the-developer/src/main/resources/application.yml
  back-end/with-the-developer/src/main/resources/mappers/teampost/teamPost.xml
Labels: :new: feat, :1234: chore

#35 [feat/security] SpringSecurity 기초 구현 (세션기반)과 자잘한 주석들 제거 및 최신 develop과 병합
  back-end/with-the-developer/build.gradle
  back-end/with-the-developer/src/main/java/com/developer/config/BeanConfig.java
  back-end/with-the-developer/src/main/java/com/developer/config/SecurityConfig.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/LoginUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/SessionSaveDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/Role.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/User.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/service/UserCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/controller/UserQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/CustomUserDetails.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/CustomUserDetailsService.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/CustomUsernameFilter.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/SecurityUtil.java
Labels: :new: feat, :1234: chore

#33 [feat/recruit/apply] 채용공고 관련 기능 구현
  back-end/with-the-developer/src/main/java/com/developer/WithTheDeveloperApplication.java
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/admin/command/dto/AdminRecruitApplyUpdateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/admin/command/service/AdminCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/controller/AdminQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/dto/RecruitApplyDetailReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/dto/RecruitApplyListReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/mapper/AdminMapper.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/service/AdminQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/common/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/controller/RecruitCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/dto/RecruitApplyDTO.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/Recruit.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/RecruitApprStatus.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/RecruitStatus.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/repository/RecruitRepository.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/service/RecruitCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/controller/RecruitQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/dto/RecruitDetailReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/dto/RecruitListReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/mapper/RecruitMapper.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/service/RecruitQueryService.java
  back-end/with-the-developer/src/main/resources/application.yml
  back-end/with-the-developer/src/main/resources/com/developer/admin/query/mapper/AdminMapper.xml
  back-end/with-the-developer/src/main/resources/com/developer/recruit/query/mapper/RecruitMapper.xml
Labels: :new: feat

#37 [feat/projectPost] 프로젝트 자랑 게시글 CRUD 기능 추가
  back-end/with-the-developer/src/main/java/com/developer/WithTheDeveloperApplication.java
  back-end/with-the-developer/src/main/java/com/developer/common/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/util/BaseEntity.java
  back-end/with-the-developer/src/main/java/com/developer/project/command/application/controller/ProjPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/project/command/application/dto/ProjPostRequestDTO.java
  back-end/with-the-developer/src/main/java/com/developer/project/command/application/service/ProjPostCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/project/command/domain/aggregate/ProjPost.java
  back-end/with-the-developer/src/main/java/com/developer/project/command/domain/repository/ProjPostRepository.java
  back-end/with-the-developer/src/main/java/com/developer/project/command/infrastructure/repository/JpaProjPostRepository.java
  back-end/with-the-developer/src/main/java/com/developer/project/query/controller/ProjPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/project/query/dto/ProjPostListResponseDTO.java
  back-end/with-the-developer/src/main/java/com/developer/project/query/dto/ProjPostResponseDTO.java
  back-end/with-the-developer/src/main/java/com/developer/project/query/mapper/ProjPostMapper.java
  back-end/with-the-developer/src/main/java/com/developer/project/query/service/ProjPostQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/service/TeamPostCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/query/service/TeamPostQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/service/UserCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/service/UserQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/CustomUserDetailsService.java
  back-end/with-the-developer/src/main/resources/application.yml
  back-end/with-the-developer/src/main/resources/mappers/project/project.xml
Labels: :new: feat

#43 [feat/swagger] Swagger 연동
  back-end/with-the-developer/build.gradle
  back-end/with-the-developer/src/main/java/com/developer/config/SwaggerConfig.java
  back-end/with-the-developer/src/main/resources/application.yml
Labels: :new: feat

#45 feat: #44 직무태그, 채용공고_직무태그 엔티티 생성
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/JobTag.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/RecruitTag.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/RecruitTagCompositeKey.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/repository/JobTagRepository.java
Labels: :new: feat

#52 [chore/alias] yml 오타 수정
  back-end/with-the-developer/src/main/resources/application.yml
Labels: :1234: chore

#51 [Feat/image] #32 amazon s3를 이용한 이미지 업로드 기능 구현
  back-end/with-the-developer/build.gradle
  back-end/with-the-developer/src/main/java/com/developer/common/util/FileUploadUtils.java
  back-end/with-the-developer/src/main/java/com/developer/comu/command/controller/ComuPostController.java
  back-end/with-the-developer/src/main/java/com/developer/config/S3Config.java
  back-end/with-the-developer/src/main/java/com/developer/image/command/dto/ImageUploadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/image/command/entity/Image.java
  back-end/with-the-developer/src/main/java/com/developer/image/command/repository/ImageRepository.java
  back-end/with-the-developer/src/main/java/com/developer/image/command/service/ImageService.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/application/controller/ProjPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/controller/RecruitCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/controller/TeamPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/service/TeamPostCommandService.java
  back-end/with-the-developer/src/main/resources/application.yml
Labels: :new: feat

#56 [feat/recruit-job-tag] 채용공고 내에 직무태그 삽입
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/admin/command/service/AdminCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/dto/RecruitApplyDetailReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/dto/RecruitApplyListReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/service/AdminQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/common/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/comu/query/service/ComuPostQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/JobTag.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/RecruitTag.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/RecruitTagCompositeKey.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/repository/JobTagRepository.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/repository/RecruitTagRepository.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/dto/RecruitApplyDTO.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/Recruit.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/service/RecruitCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/dto/RecruitDetailReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/dto/RecruitListReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/service/RecruitQueryService.java
  back-end/with-the-developer/src/main/resources/mappers/admin/AdminMapper.xml
  back-end/with-the-developer/src/main/resources/mappers/recruit/RecruitMapper.xml
Labels: :new: feat, :recycle: refactor

#58 [feat/report/entity] 신고 관련 엔티티 생성
  back-end/with-the-developer/src/main/java/com/developer/admin/command/dto/AdminRecruitApplyUpdateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/dto/RecruitApplyDetailReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/dto/RecruitApplyListReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/JobTag.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/ApprStatus.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/Recruit.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/entity/Report.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/entity/ReportReasonCategory.java
Labels: :new: feat

#63 [feat/jwt] #55 , #59 , #60 jwt 생성, SessionSaveDTO 이름 변경, SecurityUtil 사용
  .gitignore
  back-end/with-the-developer/build.gradle
  back-end/with-the-developer/src/main/java/com/developer/common/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/jwt/JwtAccessDeniedHandler.java
  back-end/with-the-developer/src/main/java/com/developer/common/jwt/JwtAuthenticationEntryPoint.java
  back-end/with-the-developer/src/main/java/com/developer/common/jwt/JwtFilter.java
  back-end/with-the-developer/src/main/java/com/developer/common/jwt/TokenDTO.java
  back-end/with-the-developer/src/main/java/com/developer/common/jwt/TokenProvider.java
  back-end/with-the-developer/src/main/java/com/developer/comu/command/controller/ComuPostController.java
  back-end/with-the-developer/src/main/java/com/developer/config/BeanConfig.java
  back-end/with-the-developer/src/main/java/com/developer/config/SecurityConfig.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/application/controller/ProjPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/controller/RecruitCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/service/RecruitCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/controller/TeamPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/TokenSaveDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/RefreshToken.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/Role.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/User.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/repository/RefreshTokenRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/service/UserCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/controller/UserQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/service/UserQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/CustomUserDetailsService.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/CustomUsernameFilter.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/SecurityUtil.java
Labels: :new: feat, :1234: chore, :recycle: refactor

#70 [Chore/image] #62 이미지 업로드 방식 수정/리팩토링
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/common/module/PostAndImageService.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/comu/command/controller/ComuPostController.java
  back-end/with-the-developer/src/main/java/com/developer/image/command/service/ImageService.java
  back-end/with-the-developer/src/main/java/com/developer/project/comment/command/application/controller/ProjCmtCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/application/controller/ProjPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/controller/RecruitCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/controller/TeamPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/controller/UserCommandController.java
Labels: :1234: chore, :recycle: refactor

#69 [feat/dbti] #68 feat: dbti완료, TestCode 작성
  .gitignore
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/application/controller/DbtiCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/application/dto/DbtiAddDTO.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/application/service/DbtiCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/domain/aggregate/Dbti.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/domain/aggregate/DbtiRole.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/domain/repository/DbtiRepository.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/infrastructure/repository/JpaDbtiRepository.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/query/controller/DbtiQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/query/dto/ResponseDbtiDTO.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/query/mapper/DbtiMapper.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/query/service/DbtiQueryService.java
  back-end/with-the-developer/src/main/resources/mappers/dbti/dbtiMapper.xml
  back-end/with-the-developer/src/test/java/com/developer/dbti/command/application/service/DbtiCommandServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/dbti/query/service/DbtiQueryServiceTest.java
Labels: :m: test, :new: feat, :1234: chore

#71 [fix] SuccessCode 패키지 import 수정
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/application/controller/DbtiCommandController.java
Labels: :hammer_and_wrench: fix

#75 [Feat/bookmark] #53 북마크 기능 구현
  back-end/with-the-developer/src/main/java/com/developer/bookmark/command/application/controller/BookmarkCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/command/application/dto/BookmarkRegistDTO.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/command/application/service/BookmarkCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/command/domain/aggregate/Bookmark.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/command/domain/repository/BookmarkRepository.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/command/infrastructure/repository/JpaBookmarkRepository.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/query/controller/BookmarkQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/query/dto/BookmarkListDTO.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/query/mapper/BookmarkMapper.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/query/service/BookmarkQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/module/PostAndBookmarkService.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/domain/aggregate/Dbti.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/command/controller/TeamPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/query/controller/TeamPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/teampost/query/service/TeamPostQueryService.java
  back-end/with-the-developer/src/main/resources/mappers/bookmark/bookmark.xml
Labels: :new: feat, :1234: chore

#81 [feat/noti] feat: 알림생성, 알림읽음, 알림삭제 처리, 테스트 작성중
  back-end/with-the-developer/src/main/java/com/developer/admin/query/service/AdminQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/application/controller/DbtiCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/domain/aggregate/DbtiRole.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/controller/NotiCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/dto/NotiCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/service/NotiCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/domain/aggregate/Noti.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/domain/aggregate/NotiType.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/domain/aggregate/PostType.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/domain/repository/NotiRepository.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/infrastructure/repository/JpaNotiRepository.java
  back-end/with-the-developer/src/main/java/com/developer/noti/query/controller/NotiQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/noti/query/dto/AllNotiDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/query/dto/ResponseNotiDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/query/mapper/NotiMapper.java
  back-end/with-the-developer/src/main/java/com/developer/noti/query/service/NotiQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/controller/RecruitCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/dto/RegisterUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/repository/UserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/service/UserCommandService.java
  back-end/with-the-developer/src/main/resources/mappers/noti/noti.xml
  back-end/with-the-developer/src/test/java/com/developer/dbti/command/application/service/DbtiCommandServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/noti/command/application/service/NotiCommandServiceTest.java
Labels: :m: test, :new: feat, :1234: chore

#84 [feat/report/create] #61 #64 #72 #84 신고 관련 기능 구현
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/admin/command/dto/AdminRecruitApplyUpdateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/admin/command/service/AdminCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/controller/AdminQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/dto/ReportDetailReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/dto/ReportListReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/mapper/AdminMapper.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/service/AdminQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/controller/RecruitCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/ApprStatus.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/Recruit.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/service/RecruitQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/controller/ReportCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/dto/ReportCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/dto/ReportCreateResultDTO.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/entity/Report.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/entity/ReportReasonCategory.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/entity/ReportType.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/repository/ReportReasonCategoryRepository.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/repository/ReportRepository.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/service/ReportCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/report/query/controller/ReportQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/User.java
  back-end/with-the-developer/src/main/resources/mappers/admin/AdminMapper.xml
Labels: :new: feat, :1234: chore, :recycle: refactor

#86 [chore/sqlSession] chore: #85 sqlSession부분 Mapper로 전체 변경
  back-end/with-the-developer/src/main/java/com/developer/admin/query/service/AdminQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/comu/comment/query/service/ComuCmtQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/service/RecruitQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/service/EmailQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/service/UserQueryService.java
Labels: :1234: chore

#88 [feat/report/activeUser] 정지된 지 10일이 경과하면 회원 상태 ACTIVE로 변경해주는 스케줄러 추가
  back-end/with-the-developer/src/main/java/com/developer/report/command/service/ReportCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/report/query/controller/ReportQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/BannedUser.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/entity/User.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/repository/BannedUserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/service/UserCommandService.java
Labels: :new: feat

#90 feat: #78 image 조회 각 게시글 조회 기능에 추가
  back-end/with-the-developer/src/main/java/com/developer/comu/comment/query/controller/ComuCmtQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/command/controller/ComuPostController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/query/controller/ComuPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/query/dto/ComuPostResponseDTO.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/query/service/ComuPostQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/dto/ProjPostResponseDTO.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/service/ProjPostQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/dto/RecruitDetailReadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/service/RecruitQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/dto/TeamPostDTO.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/service/TeamPostQueryService.java
Labels: :new: feat, :1234: chore

#92 [test/recruit] 채용공고 관련 테스트 코드 작성
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/repository/RecruitRepository.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/service/RecruitCommandService.java
  back-end/with-the-developer/src/main/resources/mappers/recruit/RecruitMapper.xml
  back-end/with-the-developer/src/test/java/com/developer/recruit/command/service/RecruitCommandServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/recruit/query/service/RecruitQueryServiceTest.java
Labels: :m: test

#94 [fix/admin/reject recruit] 채용공고 반려 시에도 특정 컬럼에 값 들어가는 문제 해결
  back-end/with-the-developer/src/main/java/com/developer/admin/command/service/AdminCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/Recruit.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/service/RecruitCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/service/ReportCommandService.java
Labels: :hammer_and_wrench: fix

#95 [Feat/team] #91 팀 모집 게시글 직무 태그 추가 기능 구현
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/TeamTag.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/TeamTagCompositeKey.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/repository/JobTagRepository.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/repository/TeamTagRepository.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/dto/TeamPostRegistDTO.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/dto/TeamPostUpdateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/entity/TeamPost.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/service/TeamPostCommandService.java
Labels: :new: feat

#100 [feat] #98 직무태그 삭제 기능 구현
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/admin/command/service/AdminCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/JobTag.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/repository/JobTagRepository.java
Labels: :new: feat

#101 [feat/goods/create] 굿즈 crud 기능 구현
  back-end/with-the-developer/src/main/java/com/developer/common/module/PostAndImageService.java
  back-end/with-the-developer/src/main/java/com/developer/goods/command/application/controller/GoodsController.java
  back-end/with-the-developer/src/main/java/com/developer/goods/command/application/dto/GoodsCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/goods/command/application/dto/GoodsUpdateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/goods/command/application/service/GoodsService.java
  back-end/with-the-developer/src/main/java/com/developer/goods/command/domain/Goods.java
  back-end/with-the-developer/src/main/java/com/developer/goods/command/infrastructure/repository/JpaGoodsRepository.java
  back-end/with-the-developer/src/main/java/com/developer/goods/query/controller/GoodsQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/goods/query/dto/GoodsResponseDTO.java
  back-end/with-the-developer/src/main/java/com/developer/goods/query/mapper/GoodsMapper.java
  back-end/with-the-developer/src/main/java/com/developer/goods/query/service/GoodsQueryService.java
  back-end/with-the-developer/src/main/resources/mappers/goods/Goods.xml
Labels: :new: feat, :hammer_and_wrench: fix

#102 [Feat/proj/team] #38 프로젝트 자랑 게시판 태그 기능 구현
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/application/controller/ProjPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/application/dto/ProjPostRequestDTO.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/application/service/ProjPostCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/domain/aggregate/ProjPost.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/domain/aggregate/ProjTag.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/domain/repository/ProjTagRepository.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/controller/ProjPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/dto/ProjPostListResponseDTO.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/dto/ProjPostResponseDTO.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/entity/TeamPost.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/dto/TeamPostDTO.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/dto/TeamPostListDTO.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/dto/TeamPostUserDTO.java
  back-end/with-the-developer/src/main/resources/application.yml
  back-end/with-the-developer/src/main/resources/mappers/project/project.xml
  back-end/with-the-developer/src/main/resources/mappers/team/post/teamPost.xml
  back-end/with-the-developer/src/main/resources/mappers/team/teamCmt.xml
  back-end/with-the-developer/src/main/resources/mappers/team/teamPost.xml
Labels: :new: feat, :1234: chore

#105 [Feat/post] #103 각 게시글 태그 검색 기능 구현
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/controller/ProjPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/mapper/ProjPostMapper.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/service/ProjPostQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/controller/RecruitCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/controller/RecruitQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/mapper/RecruitMapper.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/service/RecruitQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/controller/TeamPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/mapper/TeamPostMapper.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/service/TeamPostQueryService.java
  back-end/with-the-developer/src/main/resources/mappers/project/project.xml
  back-end/with-the-developer/src/main/resources/mappers/recruit/RecruitMapper.xml
  back-end/with-the-developer/src/main/resources/mappers/team/teamPost.xml
Labels: :new: feat
