Repository DaeChamSa/with-the-developer, pull requests merged in 2024-10, with the labels that each got.

#110 [refactor/chore/image] #106 image upload 조건 String에서 enum타입으로 변경, teamTag기능 오류 수정
  back-end/with-the-developer/src/main/java/com/developer/common/module/PostAndImageService.java
  back-end/with-the-developer/src/main/java/com/developer/image/command/dto/ImageUploadDTO.java
  back-end/with-the-developer/src/main/java/com/developer/image/command/entity/Image.java
  back-end/with-the-developer/src/main/java/com/developer/image/command/entity/ImageType.java
  back-end/with-the-developer/src/main/java/com/developer/image/command/service/ImageService.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/entity/TeamTag.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/repository/TeamTagRepository.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/entity/TeamPost.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/service/TeamPostCommandService.java
Labels: :1234: chore, :recycle: refactor

#112 [feat/order] feat: 주문 생성, 주문 취소 완료
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/order/command/application/controller/OrderCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/order/command/application/service/OrderCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/order/command/domain/aggregate/Order.java
  back-end/with-the-developer/src/main/java/com/developer/order/command/domain/repository/OrderRepository.java
  back-end/with-the-developer/src/main/java/com/developer/order/query/controller/OrderQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/order/query/dto/OrderGoodsListDTO.java
  back-end/with-the-developer/src/main/java/com/developer/order/query/dto/OrderListDTO.java
  back-end/with-the-developer/src/main/java/com/developer/order/query/dto/ResponseOrderListDTO.java
  back-end/with-the-developer/src/main/java/com/developer/order/query/mapper/OrderMapper.java
  back-end/with-the-developer/src/main/java/com/developer/order/query/service/OrderQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/payment/command/domain/aggregate/Payments.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/controller/PaymentQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/dto/ResponsePaymentDTO.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/mapper/PaymentMapper.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/service/PaymentQueryService.java
  back-end/with-the-developer/src/main/resources/mappers/order/order.xml
  back-end/with-the-developer/src/main/resources/mappers/payment/payment.xml
Labels: :new: feat, :1234: chore

#109 [feat/block] 차단 기능 개발
  back-end/with-the-developer/src/main/java/com/developer/block/command/application/controller/BlockCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/block/command/application/service/BlockCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/block/command/domain/aggregate/Block.java
  back-end/with-the-developer/src/main/java/com/developer/block/command/domain/aggregate/BlockedUser.java
  back-end/with-the-developer/src/main/java/com/developer/block/command/domain/repository/BlockRepository.java
  back-end/with-the-developer/src/main/java/com/developer/block/command/domain/repository/BlockedUserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/block/command/infrastructure/repository/JpaBlockRepository.java
  back-end/with-the-developer/src/main/java/com/developer/block/command/infrastructure/repository/JpaBlockedUserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/block/query/controller/BlockQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/block/query/dto/BlockResponseDTO.java
  back-end/with-the-developer/src/main/java/com/developer/block/query/mapper/BlockMapper.java
  back-end/with-the-developer/src/main/java/com/developer/block/query/service/BlockQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/resources/application.yml
  back-end/with-the-developer/src/main/resources/mappers/block/block.xml
Labels: :new: feat

#115 [feat/user logout] feat: 사용자 로그아웃 구현
  back-end/with-the-developer/src/main/java/com/developer/admin/command/service/AdminCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/jwt/JwtFilter.java
  back-end/with-the-developer/src/main/java/com/developer/common/jwt/TokenProvider.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/comu/comment/command/entity/ComuCmt.java
  back-end/with-the-developer/src/main/java/com/developer/comu/comment/command/service/ComuCmtService.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/command/entity/ComuPost.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/command/service/ComuPostService.java
  back-end/with-the-developer/src/main/java/com/developer/config/BeanConfig.java
  back-end/with-the-developer/src/main/java/com/developer/config/SecurityConfig.java
  back-end/with-the-developer/src/main/java/com/developer/msg/command/application/service/MessageCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/payment/command/application/service/PaymentCommandServiceImpl.java
  back-end/with-the-developer/src/main/java/com/developer/project/comment/command/application/service/ProjCmtCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/application/service/ProjPostCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/Recruit.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/service/RecruitCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/dto/ReportCreateResultDTO.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/entity/Report.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/service/ReportCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/entity/TeamPost.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/service/TeamPostCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/dto/LoginUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/dto/RegisterUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/dto/SendEmailDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/dto/TokenSaveDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/dto/UpdateUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/service/EmailCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/BannedUser.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/BlackList.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/Email.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/RefreshToken.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/Role.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/User.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/UserStatus.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/repository/BannedUserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/repository/BlackListRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/repository/EmailRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/repository/RefreshTokenRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/repository/UserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/infrastructure/repository/JpaBlackListRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/infrastructure/repository/JpaRefreshTokenRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/repository/RefreshTokenRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/mapper/BlackListMapper.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/service/BlackListQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/CustomUserDetails.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/CustomUserDetailsService.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/SecurityUtil.java
  back-end/with-the-developer/src/main/resources/mappers/user/blackListMapper.xml
Labels: :new: feat, :1234: chore

#118 feat: #117 게시판 검색 기능 구현
  back-end/with-the-developer/src/main/java/com/developer/comu/post/command/controller/ComuPostController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/query/controller/ComuPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/application/controller/ProjPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/controller/ProjPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/controller/RecruitQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/search/query/controller/SearchController.java
  back-end/with-the-developer/src/main/java/com/developer/search/query/dto/SearchIntegratedResultDTO.java
  back-end/with-the-developer/src/main/java/com/developer/search/query/dto/SearchResultDTO.java
  back-end/with-the-developer/src/main/java/com/developer/search/query/mapper/SearchMapper.java
  back-end/with-the-developer/src/main/java/com/developer/search/query/service/SearchService.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/controller/TeamPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/controller/TeamPostQueryController.java
  back-end/with-the-developer/src/main/resources/mappers/search/SearchMapper.xml
Labels: :new: feat

#125 [Feat/user-token_reissue] feat: accessToken 재발급
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/jwt/JwtFilter.java
  back-end/with-the-developer/src/main/java/com/developer/common/jwt/TokenProvider.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/service/UserCommandService.java
Labels: :new: feat, :1234: chore

#132 [feat/noti-created] feat: 채용공고, 쪽지 알림 생성
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/controller/NotiCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/dto/NotiMsgCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/dto/NotiPostCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/dto/NotiRecruitCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/service/NotiCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/domain/aggregate/Noti.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/domain/aggregate/NotiType.java
Labels: :new: feat

#129 [refactor/search] #128 2글자 이상만 검색할 수 있도록 로직 추가
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/search/query/service/SearchService.java
Labels: :recycle: refactor

#137 [feat/noti-res] feat: 알림 수신 여부 생성, 관련 메서드 생성
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/service/NotiCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/User.java
Labels: :new: feat, :1234: chore

#139 [feat/noti-isread] feat: 읽은 알림, 안읽은 알림 조회 기능 추가
  back-end/with-the-developer/src/main/java/com/developer/noti/query/controller/NotiQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/noti/query/mapper/NotiMapper.java
  back-end/with-the-developer/src/main/java/com/developer/noti/query/service/NotiQueryService.java
  back-end/with-the-developer/src/main/resources/mappers/noti/noti.xml
Labels: :new: feat

#145 [test/job-tag] #142 직무태그 관련 테스트 코드 작성
  back-end/with-the-developer/src/test/java/com/developer/admin/command/service/AdminCommandServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/goods/command/application/service/GoodsServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/goods/query/service/GoodsQueryServiceTest.java
Labels: :m: test

#141 [feat/admin-account] feat: 관리자 계정 자동 생성, admin 주소는 admin 권한만 접근가능, chore: 폴더 구조 변경, Security 필요 권한 ROLE_ 부여
  back-end/with-the-developer/src/main/java/com/developer/common/module/AdminAccountInitializer.java
  back-end/with-the-developer/src/main/java/com/developer/config/SecurityConfig.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/dto/UpdateUserDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/User.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/repository/UserRepository.java
  back-end/with-the-developer/src/main/java/com/developer/user/security/CustomUserDetails.java
Labels: :new: feat, :1234: chore

#151 [feat] #147 신고 사유 카테고리 삭제 기능 구현
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/admin/command/service/AdminCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/repository/ReportReasonCategoryRepository.java
Labels: :new: feat

#153 refactor: #152 스케줄링 시간 간격 변경
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/service/RecruitCommandService.java
Labels: :recycle: refactor

#150 [feat, test/cart goods/create] 장바구니 기능, 테스트 코드 구현
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/application/controller/CartGoodsController.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/application/dto/CartGoodsAddDTO.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/application/service/CartGoodsService.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/domain/aggregate/CartGoods.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/domain/aggregate/CartGoodsCompositeKey.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/infrastructure/repository/CartGoodsRepository.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/query/controller/CartGoodsQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/query/dto/CartGoodsQueryDTO.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/query/mapper/CartGoodsMapper.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/query/service/CartGoodsQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/goods/command/application/service/GoodsService.java
  back-end/with-the-developer/src/main/resources/mappers/cartGoods/CartGoods.xml
  back-end/with-the-developer/src/test/java/com/developer/cartGoods/command/application/service/CartGoodsServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/cartGoods/query/service/CartGoodsQueryServiceTest.java
Labels: :m: test, :new: feat

#157 [refactor/package] user import 수정
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/application/service/CartGoodsService.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/domain/aggregate/CartGoods.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/infrastructure/repository/CartGoodsRepository.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/query/service/CartGoodsQueryService.java
Labels: :recycle: refactor

#149 [feat/user-setting] feat: 비밀번호 재설정
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/dto/PwResettingDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/User.java
Labels: :new: feat

#161 [refactor/test-user-import] user import 수정
  back-end/with-the-developer/src/test/java/com/developer/cartGoods/command/application/service/CartGoodsServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/cartGoods/query/service/CartGoodsQueryServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/comu/post/command/service/ComuPostServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/comu/post/query/service/ComuPostQueryServiceTest.java
Labels: :recycle: refactor

#146 [test/comu-cmt] #143 커뮤니티 댓글 crud 테스트 구현 완료
  back-end/with-the-developer/src/test/java/com/developer/comu/comment/command/service/ComuCmtServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/comu/comment/query/service/ComuCmtQueryServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/comu/post/command/service/ComuPostServiceTest.java
Labels: :m: test

#162 [refactor/test-user-import] user import 수정
  back-end/with-the-developer/src/test/java/com/developer/comu/comment/command/service/ComuCmtServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/comu/comment/query/service/ComuCmtQueryServiceTest.java
Labels: :recycle: refactor

#160 [feat/prefix-create] feat: 수식어 생성 및 조회 가능
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/command/application/controller/PrefixCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/command/application/dto/PrefixCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/command/application/service/PrefixCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/command/domain/aggregate/Prefix.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/command/domain/repository/PrefixRepository.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/command/infrastructure/repository/JpaPrefixRepository.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/query/controller/PrefixQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/query/dto/MapperPrefixDTO.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/query/dto/ResponsePrefixDTO.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/query/mapper/PrefixMapper.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/query/service/PrefixQueryService.java
  back-end/with-the-developer/src/main/resources/mappers/prefix/prefix.xml
Labels: :new: feat

#168 [feat/readme] readme 작성
  README.md
Labels: :memo: docs

#165 [feat/module-job_tag] feat: 초기 직무 태그 생성, 초기 성향 생성
  .gitignore
  back-end/with-the-developer/src/main/java/com/developer/common/module/DbtiInitializer.java
  back-end/with-the-developer/src/main/java/com/developer/common/module/JobTagInitializer.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/domain/repository/DbtiRepository.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/command/entity/JobTag.java
  back-end/with-the-developer/src/main/java/com/developer/order/command/application/service/OrderCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/controller/RecruitCommandController.java
Labels: :new: feat, :1234: chore

#175 [chore/package-import] jobTag 패키지 import 수정
  back-end/with-the-developer/src/main/java/com/developer/common/module/JobTagInitializer.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/command/application/service/PrefixCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/query/service/PrefixQueryService.java
Labels: :1234: chore

#155 [test/report-category] 신고 사유 카테고리 관련 테스트 코드 작성
  back-end/with-the-developer/src/test/java/com/developer/admin/command/service/AdminCommandServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/comu/post/command/service/ComuPostServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/comu/post/query/service/ComuPostQueryServiceTest.java
Labels: :m: test

#173 docs/readme 리드미 작성
  README.md
Labels: :memo: docs

#179 [Chore/send-noti] chore: comment 생성 및 쪽지 발송, 채용공고 승인시 알림 보내는 로직 추가, TeamCmtRegistDTO, TeamPostRegistDTO 수정
  back-end/with-the-developer/src/main/java/com/developer/admin/command/service/AdminCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/comu/comment/command/service/ComuCmtService.java
  back-end/with-the-developer/src/main/java/com/developer/msg/command/application/service/MessageCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/dto/NotiCommentCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/dto/NotiMsgCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/dto/NotiRecruitCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/service/NotiCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/domain/aggregate/NotiType.java
  back-end/with-the-developer/src/main/java/com/developer/project/comment/command/application/service/ProjCmtCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/team/comment/command/dto/TeamCmtRegistDTO.java
  back-end/with-the-developer/src/main/java/com/developer/team/comment/command/service/TeamCmtCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/dto/TeamPostRegistDTO.java
Labels: :new: feat, :1234: chore

#177 docs/readme 수정
  README.md
Labels: :memo: docs

#184 [Feat/payment-query] feat: 결제 내역 전체 조회 결제 코드로 내역 조회 결제 내역 상태별 전체 조회
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer/src/main/java/com/developer/payment/command/application/service/PaymentCommandServiceImpl.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/controller/PaymentQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/dto/ResponsePaymentDTO.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/mapper/PaymentMapper.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/service/PaymentQueryService.java
  back-end/with-the-developer/src/main/resources/mappers/payment/payment.xml
Labels: :new: feat

#185 docs: README.md
  README.md
Labels: :memo: docs

#171 [chore/swagger] swagger 그룹 설정
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/controller/AdminQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/block/command/application/controller/BlockCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/block/query/controller/BlockQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/command/application/controller/BookmarkCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/query/controller/BookmarkQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/application/controller/CartGoodsController.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/query/controller/CartGoodsQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/comment/command/controller/ComuCmtController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/comment/query/controller/ComuCmtQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/command/controller/ComuPostController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/query/controller/ComuPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/application/controller/DbtiCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/query/controller/DbtiQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/query/service/DbtiQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/goods/command/application/controller/GoodsController.java
  back-end/with-the-developer/src/main/java/com/developer/goods/query/controller/GoodsQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/query/Controller/JobTagQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/msg/command/application/controller/MessageCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/msg/query/controller/MessageQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/controller/NotiCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/noti/query/controller/NotiQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/order/command/application/controller/OrderCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/order/query/controller/OrderQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/payment/command/application/controller/PaymentCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/controller/PaymentQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/command/application/controller/PrefixCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/query/controller/PrefixQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/project/comment/command/application/controller/ProjCmtCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/project/comment/query/controller/ProjCmtQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/command/application/controller/ProjPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/controller/ProjPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/controller/RecruitCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/controller/RecruitQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/controller/ReportCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/search/query/controller/SearchController.java
  back-end/with-the-developer/src/main/java/com/developer/team/comment/command/controller/TeamCmtCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/team/comment/query/controller/TeamCmtQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/controller/TeamPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/controller/TeamPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/controller/UserQueryController.java
Labels: :1234: chore

#188 test: #187 UserCommandTest
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/dto/NotiCommentCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/dto/NotiMsgCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/dto/NotiRecruitCreateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/User.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/repository/EmailRepository.java
  back-end/with-the-developer/src/test/java/com/developer/user/command/application/service/UserCommandServiceTest.java
Labels: :new: feat

#189 docs: README.md
  README.md
Labels: :memo: docs

#190 chore: #166 swagger 설명 추가
  back-end/with-the-developer/src/main/java/com/developer/admin/query/controller/AdminQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/goods/query/controller/GoodsQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/controller/PaymentQueryController.java
Labels: :1234: chore

#194 refactor: #193 검색 시 삭제된 항목은 보이지 않도록 리펙토링
  back-end/with-the-developer/src/main/resources/mappers/search/SearchMapper.xml
Labels: :recycle: refactor

#196 [refactor/block] 본인 차단 불가, 없는 회원 차단 예외 처리
  back-end/with-the-developer/src/main/java/com/developer/block/command/application/service/BlockCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/common/exception/ErrorCode.java
Labels: :recycle: refactor

#198 refactor: #197 승인상태가 approve가 아닌 것을 상세 조회할 경우에 대한 예외처리
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/entity/ApprStatus.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/service/RecruitQueryService.java
  back-end/with-the-developer/src/main/resources/mappers/recruit/RecruitMapper.xml
Labels: :recycle: refactor

#191 docs/readme3: 회고, 기술 스택 수정
  README.md
Labels: :memo: docs

#204 [Chore/structure] chore: JSON Mapping 안되는 것들 name처리, 아이디 찾기 전용 이메일검증 추가
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/command/application/dto/BookmarkRegistDTO.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/application/controller/CartGoodsController.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/query/controller/CartGoodsQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/common/jwt/TokenProvider.java
  back-end/with-the-developer/src/main/java/com/developer/common/module/GoodsInitializer.java
  back-end/with-the-developer/src/main/java/com/developer/goods/query/controller/GoodsQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/msg/command/application/controller/MessageCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/msg/command/application/service/MessageCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/order/query/dto/OrderListDTO.java
  back-end/with-the-developer/src/main/java/com/developer/order/query/service/OrderQueryService.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/controller/ReportCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/team/comment/command/dto/TeamCmtUpdateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/team/comment/query/dto/ResponseTeamCmtListDTO.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/dto/TeamPostUpdateDTO.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/service/EmailCommandService.java
Labels: :new: feat, :1234: chore

#209 chore: #208 yml 파일에서 DB 정보, jwt.secret값 API-KET.properties에서 가져오는걸로 변경
  back-end/with-the-developer-user-service/src/main/resources/application.yml
Labels: :1234: chore, :recycle: refactor

#213 [refector/refreshToken-redis] 리프레시 토큰 테이블 레디스로 변경
  back-end/with-the-developer-user-service/build.gradle
  back-end/with-the-developer-user-service/src/main/java/com/developer/WithTheDeveloperUserServiceApplication.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/common/jwt/ReissueTokenDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/common/jwt/TokenProvider.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/config/RedisConfig.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/domain/aggregate/RefreshTokenRedis.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/domain/repository/RefreshTokenRedisRepository.java
  back-end/with-the-developer-user-service/src/main/resources/application.yml
Labels: :new: feat, :recycle: refactor

#221 [refactor/report] #216 핸들러 이용해서 신고 기능 코드 리팩토링
  README.md
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/admin/command/service/AdminCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/controller/NotiCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/repository/RecruitRepository.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/command/service/RecruitCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/service/ComuReportHandler.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/service/ProjPostReportHandler.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/service/RecruitReportHandler.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/service/ReportCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/service/ReportHandler.java
  back-end/with-the-developer/src/main/java/com/developer/report/command/service/TeamPostReportHandler.java
Labels: :recycle: refactor

#223 refector: #222 refector: #222 DTO 생일 타입 LocalDate로 변경 및 사용자 관련 DTO @Valid로 유효성 검사 추가, 사용자 컬럼들 중복일시 가입 및 수정 불가
  back-end/with-the-developer-user-service/src/main/java/com/developer/common/exception/GlobalExceptionHandler.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/common/success/SuccessCode.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/dto/LoginUserDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/dto/PwResettingDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/dto/RegisterUserDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/dto/SendEmailDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/dto/UpdateUserDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/domain/aggregate/User.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/query/controller/UserQueryController.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/query/dto/CheckCodeDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/query/dto/FindIdDTO.java
Labels: :new: feat, :recycle: refactor

#224 [refactor/exceptions] #215 테스트하며 발생한 문제 처리
  back-end/with-the-developer/src/main/java/com/developer/common/module/ReportReasonCategoryInitializer.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/dto/TeamPostRegistDTO.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/service/TeamPostCommandService.java
Labels: :recycle: refactor

#214 [Docs/Chore] #211 README 수정, REST API 설계에 맞게 엔드포인트 수정
  README.md
  back-end/with-the-developer/src/main/java/com/developer/admin/command/controller/AdminCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/admin/query/controller/AdminQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/bookmark/command/application/controller/BookmarkCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/command/application/controller/CartGoodsController.java
  back-end/with-the-developer/src/main/java/com/developer/cartGoods/query/controller/CartGoodsQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/comment/command/controller/ComuCmtController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/comment/command/service/ComuCmtService.java
  back-end/with-the-developer/src/main/java/com/developer/comu/comment/query/controller/ComuCmtQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/command/controller/ComuPostController.java
  back-end/with-the-developer/src/main/java/com/developer/comu/post/query/controller/ComuPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/command/application/controller/DbtiCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/dbti/query/controller/DbtiQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/goods/command/application/controller/GoodsController.java
  back-end/with-the-developer/src/main/java/com/developer/goods/query/controller/GoodsQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/jobTag/query/Controller/JobTagQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/msg/command/application/controller/MessageCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/msg/query/controller/MessageQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/noti/command/application/controller/NotiCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/order/command/application/controller/OrderCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/order/query/controller/OrderQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/payment/command/application/controller/PaymentCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/payment/query/controller/PaymentQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/command/application/controller/PrefixCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/prefix/query/controller/PrefixQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/project/comment/query/controller/ProjCmtQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/project/post/query/controller/ProjPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/recruit/query/controller/RecruitQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/search/query/controller/SearchController.java
  back-end/with-the-developer/src/main/java/com/developer/team/comment/query/controller/TeamCmtQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/command/controller/TeamPostCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/team/post/query/controller/TeamPostQueryController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  back-end/with-the-developer/src/main/java/com/developer/user/command/domain/aggregate/User.java
  back-end/with-the-developer/src/main/java/com/developer/user/query/controller/UserQueryController.java
  back-end/with-the-developer/src/test/java/com/developer/comu/comment/command/service/ComuCmtServiceTest.java
  back-end/with-the-developer/src/test/java/com/developer/user/command/application/service/UserCommandServiceTest.java
Labels: :memo: docs, :1234: chore

#226 refector: #225 이메일 컬럼 삭제, 아이디 찾기 기능 필요 데이터 변경
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/dto/LoginUserDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/dto/PwResettingDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/dto/RegisterUserDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/dto/SendEmailDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/dto/UpdateUserDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/service/EmailCommandService.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/domain/aggregate/Email.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/domain/aggregate/User.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/command/domain/repository/UserRepository.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/query/controller/UserQueryController.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/query/dto/CheckCodeDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/query/dto/FindIdDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/query/dto/ResponseUserDTO.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/query/mapper/UserMapper.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/query/service/EmailQueryService.java
  back-end/with-the-developer-user-service/src/main/java/com/developer/user/query/service/UserQueryService.java
  back-end/with-the-developer-user-service/src/main/resources/mappers/user/emailMapper.xml
  back-end/with-the-developer-user-service/src/main/resources/mappers/user/userMapper.xml
Labels: :new: feat, :recycle: refactor

#229 docs: #228 프론트엔트 프로젝트 디렉토리 생성
  .gitignore
  front-end/with-the-developer/README.md
  front-end/with-the-developer/index.html
  front-end/with-the-developer/jsconfig.json
  front-end/with-the-developer/package-lock.json
  front-end/with-the-developer/package.json
  front-end/with-the-developer/public/favicon.ico
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/assets/test.md
  front-end/with-the-developer/src/components/test.md
  front-end/with-the-developer/src/main.js
  front-end/with-the-developer/src/router/test.md
  front-end/with-the-developer/src/store/test.md
  front-end/with-the-developer/src/views/test.md
  front-end/with-the-developer/vite.config.js
Labels: :memo: docs

#236 [feat/components-mypage] feat: 공용 컴포넌트 Mypage 사이드바 생성
  front-end/with-the-developer/src/components/MypageSideBar.vue
  front-end/with-the-developer/src/components/test.md
Labels: :new: feat, :1234: chore

#239 [feat/footer] 컴포넌트 추가
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/components/Footer.vue
  front-end/with-the-developer/src/main.js
Labels: :new: feat

#241 [feat/tos-page] feat: #240 약관동의 페이지 | merge: feat/tos-page , develop
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/views/TosView.vue
  front-end/with-the-developer/src/views/test.md
Labels: :new: feat

#245 feat: #244 서치바 컴포넌트 디자인 및 라우팅
  front-end/with-the-developer/package-lock.json
  front-end/with-the-developer/package.json
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/components/SearchBar.vue
  front-end/with-the-developer/src/main.js
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/SearchResults.vue
Labels: :new: feat

#246 [Feat/admin goods] #242 관리자 굿즈 페이지
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/main.js
  front-end/with-the-developer/src/views/AdminGoods.vue
Labels: :new: feat

#257 [Feat/job tag] #249 관리자 페이지 직무, 신고, 성향 태그 구현 완료
  front-end/with-the-developer/src/views/Admin-Tag.vue
Labels: :new: feat

#256 [feat/register-page] feat: #255 백엔드 아이디, 닉네임, 핸드폰번호 중복검증 생성, 프론트 유효성검사 도입
  back-end/with-the-developer-msa/with-the-developer-gateway/src/main/resources/application.yml
  back-end/with-the-developer-msa/with-the-developer-user-service/src/main/java/com/developer/userservice/user/query/controller/UserQueryController.java
  back-end/with-the-developer-msa/with-the-developer-user-service/src/main/java/com/developer/userservice/user/query/mapper/UserMapper.java
  back-end/with-the-developer-msa/with-the-developer-user-service/src/main/java/com/developer/userservice/user/query/service/UserQueryService.java
  back-end/with-the-developer-msa/with-the-developer-user-service/src/main/resources/mappers/user/userMapper.xml
  front-end/with-the-developer/package-lock.json
  front-end/with-the-developer/package.json
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/assets/test.md
  front-end/with-the-developer/src/router/test.md
  front-end/with-the-developer/src/views/RegisterView.vue
  front-end/with-the-developer/src/views/TosView.vue
Labels: :new: feat

#252 [Feat/components main] #243 로그인 전/후 메인페이지 구현
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/components/NavigationBar.vue
  front-end/with-the-developer/src/views/MainPage-Before-Login.vue
  front-end/with-the-developer/src/views/MainPageAfter.vue
  front-end/with-the-developer/src/views/MainPageBefore.vue
Labels: :new: feat

#261 [feat/admin-goodsRegister] #260 관리자 굿즈 등록 화면
  front-end/with-the-developer/src/views/Admin-GoodsRegister.vue
Labels: :new: feat

#259 chore/admin-sidebar #258 관리자 사이드바 신고관리 삭제, 회원관리 내에서 신고횟수 관리 예정
  front-end/with-the-developer/src/components/AdminSideBar.vue
Labels: :1234: chore

#264 [feat/login-page] feat: #263 로그인 페이지 완성, 백엔드에서 로그인시 반환값 Bearer 제거
  back-end/with-the-developer-msa/with-the-developer-gateway/src/main/resources/application.yml
  back-end/with-the-developer-msa/with-the-developer-user-service/src/main/java/com/developer/userservice/user/command/application/controller/UserCommandController.java
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/components/NavigationBar.vue
  front-end/with-the-developer/src/main.js
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/LoginView.vue
  front-end/with-the-developer/src/views/RegisterView.vue
  front-end/with-the-developer/src/views/TosView.vue
Labels: :new: feat, :1234: chore

#268 [feat/findid-page] feat: #266 아이디찾기 페이지 완료, 백엔드 아이디 찾기 반환값 중 "사용자 아이디: " 부분 삭제
  back-end/with-the-developer-msa/with-the-developer-user-service/src/main/java/com/developer/userservice/user/query/controller/UserQueryController.java
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/FindIdView.vue
  front-end/with-the-developer/src/views/LoginView.vue
Labels: :new: feat, :1234: chore

#271 [feat: #269 비밀번호 재설정 페이지]
  front-end/with-the-developer/src/views/FindIdView.vue
  front-end/with-the-developer/src/views/ReSettingPwPage.vue
  front-end/with-the-developer/src/views/RegisterView.vue
Labels: :new: feat

#270 [feat/admin-user] #267 관리자 회원 관리 목록 화면 구현
  front-end/with-the-developer/src/views/Admin-User.vue
Labels: :new: feat

#274 [chore/admin user] 관리자 굿즈 페이지
  back-end/with-the-developer-monolithic/src/main/java/com/developer/config/SecurityConfig.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/goods/query/controller/GoodsQueryController.java
  front-end/with-the-developer/src/views/AdminGoods.vue
Labels: :1234: chore

#278 Feat/admin blockselect #275 관리자 신고 승인 페이지
  front-end/with-the-developer/src/views/AdminBlock.vue
Labels: :new: feat

#277 feat/user-sendBlock #276 회원 신고 전송창 구현
  front-end/with-the-developer/src/views/UserBlock.vue
Labels: :new: feat

#286 [feat/cart] 장바구니가 비었을 때 로직 추가
  back-end/with-the-developer-monolithic/src/main/java/com/developer/cartGoods/query/service/CartGoodsQueryService.java
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/main.js
  front-end/with-the-developer/src/router/MainRouter.js
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/Cart.vue
Labels: :new: feat, :recycle: refactor

#287 chore: 빠진 괄호 추가
  back-end/with-the-developer-monolithic/src/main/java/com/developer/cartGoods/query/service/CartGoodsQueryService.java
Labels: :1234: chore

#290 [feat/pay/fail] 결제 실패 화면 디자인 및 라우팅
  back-end/with-the-developer-monolithic/src/main/java/com/developer/cartGoods/query/service/CartGoodsQueryService.java
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/PayComplete.vue
  front-end/with-the-developer/src/views/PayFail.vue
Labels: :new: feat

#292 feat: #288 성향테스트 결과 페이지, store 추가 vuex로 로그인, 로그아웃 상태관리
  back-end/with-the-developer-monolithic/src/main/java/com/developer/dbti/query/controller/DbtiQueryController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/dbti/query/mapper/DbtiMapper.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/dbti/query/service/DbtiQueryService.java
  back-end/with-the-developer-monolithic/src/main/resources/mappers/dbti/dbtiMapper.xml
  front-end/with-the-developer/package-lock.json
  front-end/with-the-developer/package.json
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/components/NavigationBar.vue
  front-end/with-the-developer/src/main.js
  front-end/with-the-developer/src/router/MainRouter.js
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/store/store.js
  front-end/with-the-developer/src/store/test.md
  front-end/with-the-developer/src/views/DbtiResultView.vue
  front-end/with-the-developer/src/views/DbtiTestView.vue
  front-end/with-the-developer/src/views/LoginView.vue
Labels: :new: feat, :1234: chore

#296 [fix/cart] 장바구니 에러 해결 및 리펙토링
  back-end/with-the-developer-monolithic/src/main/resources/mappers/cartGoods/CartGoods.xml
  front-end/with-the-developer/src/views/Cart.vue
Labels: :hammer_and_wrench: fix, :recycle: refactor

#294 [Chore/admin sidebar] #293 관리자 회원, 굿즈 페이지 사이드바, 라우터 적용 및 페이징처리 공통파일로 수정
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/components/AdminSideBar.vue
  front-end/with-the-developer/src/components/Pagination.js
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/Admin-User.vue
  front-end/with-the-developer/src/views/AdminBlock.vue
  front-end/with-the-developer/src/views/AdminGoods.vue
  front-end/with-the-developer/src/views/UserBlock.vue
Labels: :1234: chore

#299 chore: #298 로그인 유효성 검사 변경, 회원가입 버튼 주소 변경
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/command/application/dto/LoginUserDTO.java
  front-end/with-the-developer/src/views/RegisterView.vue
Labels: :1234: chore

#304 [feat/job-select] 직무 태그 선택
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/DbtiResultView.vue
  front-end/with-the-developer/src/views/JobSelectView.vue
  front-end/with-the-developer/src/views/LoginView.vue
Labels: :new: feat

#305 [feat/blue-modal] #297 주문 모달 컴포넌트 생성 및 연결
  front-end/with-the-developer/src/components/blueModal.vue
  front-end/with-the-developer/src/views/Cart.vue
Labels: :new: feat

#307 feat: #306 수식어 최종 결과 페이지
  back-end/with-the-developer-monolithic/src/main/java/com/developer/common/module/DbtiInitializer.java
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/DbtiResultView.vue
  front-end/with-the-developer/src/views/JobSelectView.vue
  front-end/with-the-developer/src/views/LoginView.vue
  front-end/with-the-developer/src/views/PrefixResultView.vue
  front-end/with-the-developer/src/views/RegisterView.vue
Labels: :new: feat

#313 [feat/community] 커뮤니티 게시판 구현
  back-end/with-the-developer-monolithic/src/main/java/com/developer/comu/comment/query/dto/ComuCmtDTO.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/comu/post/query/dto/ComuPostResponseDTO.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/comu/post/query/dto/ComuPostUserDTO.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/config/SecurityConfig.java
  back-end/with-the-developer-monolithic/src/main/resources/mappers/comu/ComuComment.xml
  back-end/with-the-developer-monolithic/src/main/resources/mappers/comu/ComuPost.xml
  front-end/with-the-developer/package-lock.json
  front-end/with-the-developer/package.json
  front-end/with-the-developer/src/components/CommunityBoardList.vue
  front-end/with-the-developer/src/config/image-base-url.js
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/CommunityBoardView.vue
  front-end/with-the-developer/src/views/CommunityCreateView.vue
  front-end/with-the-developer/src/views/CommunityPostView.vue
  front-end/with-the-developer/src/views/CommunityUpdateView.vue
Labels: :new: feat

#311 [feat/goods-list] 굿즈 목록 조회 기능 구현
  back-end/with-the-developer-monolithic/src/main/java/com/developer/goods/query/service/GoodsQueryService.java
  front-end/with-the-developer/src/components/SearchBar.vue
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/GoodsList.vue
Labels: :new: feat, :recycle: refactor

#314 [refactor/community] 모달창 생성 시 모달창이 가장 위로 출력
  front-end/with-the-developer/src/views/CommunityPostView.vue
Labels: :recycle: refactor

#309 chore: #308 view 폴더 구분, 라우터 분할
  back-end/with-the-developer-monolithic/src/main/java/com/developer/noti/command/application/controller/NotiCommandController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/noti/command/application/dto/NotiAllDTO.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/noti/command/application/service/NotiCommandService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/noti/command/domain/aggregate/Noti.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/noti/command/domain/repository/NotiRepository.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/noti/query/controller/NotiQueryController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/noti/query/mapper/NotiMapper.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/noti/query/service/NotiQueryService.java
  back-end/with-the-developer-monolithic/src/main/resources/mappers/noti/noti.xml
  back-end/with-the-developer-monolithic/src/test/java/com/developer/noti/command/application/service/NotiCommandServiceTest.java
  back-end/with-the-developer-monolithic/src/test/java/com/developer/noti/query/service/NotiQueryServiceTest.java
  front-end/with-the-developer/package-lock.json
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/components/NavigationBar.vue
  front-end/with-the-developer/src/components/NotiModal.vue
  front-end/with-the-developer/src/main.js
  front-end/with-the-developer/src/router/PrefixRouter.js
  front-end/with-the-developer/src/router/UserRouter.js
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/prefix/DbtiResultView.vue
  front-end/with-the-developer/src/views/prefix/DbtiTestView.vue
  front-end/with-the-developer/src/views/prefix/JobSelectView.vue
  front-end/with-the-developer/src/views/prefix/PrefixResultView.vue
  front-end/with-the-developer/src/views/user/FindIdView.vue
  front-end/with-the-developer/src/views/user/LoginView.vue
  front-end/with-the-developer/src/views/user/ReSettingPwPage.vue
  front-end/with-the-developer/src/views/user/RegisterView.vue
  front-end/with-the-developer/src/views/user/TosView.vue
Labels: :new: feat, :1234: chore

#322 [feat/project] 프로젝트 자랑 게시판 View 구현
  back-end/with-the-developer-monolithic/src/main/java/com/developer/project/comment/query/dto/ProjCmtResponseDTO.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/project/post/command/application/controller/ProjPostCommandController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/project/post/command/application/dto/ProjPostRequestDTO.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/project/post/query/dto/ProjPostListResponseDTO.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/project/post/query/dto/ProjPostResponseDTO.java
  back-end/with-the-developer-monolithic/src/main/resources/mappers/project/project-comment.xml
  back-end/with-the-developer-monolithic/src/main/resources/mappers/project/project.xml
  front-end/with-the-developer/src/components/ProjectBoardList.vue
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/community/CommunityBoardView.vue
  front-end/with-the-developer/src/views/community/CommunityCreateView.vue
  front-end/with-the-developer/src/views/community/CommunityPostView.vue
  front-end/with-the-developer/src/views/community/CommunityUpdateView.vue
  front-end/with-the-developer/src/views/project/ProjectBoardView.vue
  front-end/with-the-developer/src/views/project/ProjectCreateView.vue
  front-end/with-the-developer/src/views/project/ProjectPostView.vue
  front-end/with-the-developer/src/views/project/ProjectUpdateView.vue
Labels: :new: feat

#325 chore: #324 없어진 토글 연결, 로그인시에만 알림 가져오는 로직 추가, 10분마다 알림 가져오는 로직추가, 테스트 …
  front-end/with-the-developer/src/components/NavigationBar.vue
  front-end/with-the-developer/src/components/NotiModal.vue
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/prefix/DbtiResultView.vue
  front-end/with-the-developer/src/views/prefix/DbtiTestView.vue
  front-end/with-the-developer/src/views/prefix/JobSelectView.vue
  front-end/with-the-developer/src/views/user/FindIdView.vue
  front-end/with-the-developer/src/views/user/LoginView.vue
  front-end/with-the-developer/src/views/user/RegisterView.vue
Labels: :1234: chore

#316 [feat/goods-details] 굿즈 상세 조회 기능 구현
  front-end/with-the-developer/src/components/Pagination.js
  front-end/with-the-developer/src/components/blueModal.vue
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/Cart.vue
  front-end/with-the-developer/src/views/GoodsDetail.vue
  front-end/with-the-developer/src/views/GoodsList.vue
Labels: :new: feat

#320 [chore/admin goods] 관리자 굿즈 조회, 등록, 삭제 기능 구현, 폴더 구조 정리
  back-end/with-the-developer-monolithic/src/main/java/com/developer/goods/command/application/controller/GoodsController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/goods/command/application/service/GoodsService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/goods/query/controller/GoodsQueryController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/goods/query/dto/GoodsResponseDTO.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/goods/query/mapper/GoodsMapper.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/goods/query/service/GoodsQueryService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/command/application/dto/LoginUserDTO.java
  back-end/with-the-developer-monolithic/src/main/resources/mappers/goods/Goods.xml
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/components/Pagination.js
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/AdminGoods.vue
  front-end/with-the-developer/src/views/admin/Admin-GoodsRegister.vue
  front-end/with-the-developer/src/views/admin/Admin-Tag.vue
  front-end/with-the-developer/src/views/admin/Admin-User.vue
  front-end/with-the-developer/src/views/admin/AdminBlock.vue
  front-end/with-the-developer/src/views/admin/AdminGoods.vue
Labels: :hammer_and_wrench: fix, :1234: chore, :recycle: refactor

#327 [chore/admin goods] 관리자 권한 적용
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/admin/Admin-GoodsRegister.vue
  front-end/with-the-developer/src/views/admin/AdminGoods.vue
  front-end/with-the-developer/src/views/admin/AdminGoodsDetail.vue
Labels: :hammer_and_wrench: fix, :1234: chore

#333 [feat/order] 주문 및 결제 정보 생성
  back-end/with-the-developer-monolithic/src/main/java/com/developer/payment/command/application/controller/PaymentCommandController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/payment/query/controller/PaymentQueryController.java
  front-end/with-the-developer/src/components/blueModal.vue
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/Cart.vue
Labels: :new: feat

#334 [Chore/dbti-result] chore: #332 dbti 결과페이지 css 및 기능 수정, jobTag 선택 페이지 css 및 기능 수정, 불필요한 import 구문 제거
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/command/application/dto/LoginUserDTO.java
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/components/NotiModal.vue
  front-end/with-the-developer/src/views/prefix/DbtiResultView.vue
  front-end/with-the-developer/src/views/prefix/DbtiTestView.vue
  front-end/with-the-developer/src/views/prefix/JobSelectView.vue
  front-end/with-the-developer/src/views/user/FindIdView.vue
  front-end/with-the-developer/src/views/user/LoginView.vue
  front-end/with-the-developer/src/views/user/ReSettingPwPage.vue
  front-end/with-the-developer/src/views/user/RegisterView.vue
Labels: :new: feat, :1234: chore

#336 [Feat/mypage] #329 마이페이지 내 게시글 목록 기능 구현
  back-end/with-the-developer-monolithic/src/main/java/com/developer/comu/post/query/controller/ComuPostQueryController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/comu/post/query/mapper/ComuPostMapper.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/comu/post/query/service/ComuPostQueryService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/project/post/query/controller/ProjPostQueryController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/project/post/query/mapper/ProjPostMapper.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/project/post/query/service/ProjPostQueryService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/recruit/query/controller/RecruitQueryController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/recruit/query/mapper/RecruitMapper.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/recruit/query/service/RecruitQueryService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/team/post/query/controller/TeamPostQueryController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/team/post/query/dto/TeamPostDTO.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/team/post/query/mapper/TeamPostMapper.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/team/post/query/service/TeamPostQueryService.java
  back-end/with-the-developer-monolithic/src/main/resources/mappers/comu/ComuPost.xml
  back-end/with-the-developer-monolithic/src/main/resources/mappers/project/project.xml
  back-end/with-the-developer-monolithic/src/main/resources/mappers/recruit/RecruitMapper.xml
  back-end/with-the-developer-monolithic/src/main/resources/mappers/team/teamPost.xml
  front-end/with-the-developer/src/components/MypagePostMenu.vue
  front-end/with-the-developer/src/components/MypageSideBar.vue
  front-end/with-the-developer/src/router/MyPageRouter.js
  front-end/with-the-developer/src/views/MypageProfile.vue
  front-end/with-the-developer/src/views/mypage/bookmark/MyPageRecruitBookmark.vue
  front-end/with-the-developer/src/views/mypage/post/MyPageComuPost.vue
  front-end/with-the-developer/src/views/mypage/post/MyPageProjectPost.vue
  front-end/with-the-developer/src/views/mypage/post/MyPageRecruitPost.vue
  front-end/with-the-developer/src/views/mypage/post/MyPageTeamPost.vue
Labels: :new: feat

#337 feat: #335 404 에러페이지 제작 및 약관동의 내용 기입
  front-end/with-the-developer/src/components/blueModal.vue
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/Cart.vue
  front-end/with-the-developer/src/views/error/NotFound.vue
  front-end/with-the-developer/src/views/main/MainPageAfter.vue
  front-end/with-the-developer/src/views/main/MainPageBefore.vue
  front-end/with-the-developer/src/views/prefix/DbtiTestView.vue
  front-end/with-the-developer/src/views/user/ReSettingPwPage.vue
  front-end/with-the-developer/src/views/user/RegisterView.vue
  front-end/with-the-developer/src/views/user/TosView.vue
Labels: :new: feat, :1234: chore

#343 [chore] 중복 필드 제거
  back-end/with-the-developer-monolithic/src/main/java/com/developer/team/post/query/dto/TeamPostDTO.java
Labels: :1234: chore

#345 chore: #344 네비바 비로그인 마이페이지선택시 로그인 창으로 이동 및 다른 버튼들 클릭시 화면 안나오는 문제 해결
  front-end/with-the-developer/src/components/NavigationBar.vue
Labels: :1234: chore

#348 [feat/post] bookmark 등록
  front-end/with-the-developer/src/components/CommunityBoardList.vue
  front-end/with-the-developer/src/components/ProjectBoardList.vue
  front-end/with-the-developer/src/components/TeamBoardList.vue
  front-end/with-the-developer/src/views/community/CommunityBoardView.vue
  front-end/with-the-developer/src/views/community/CommunityPostView.vue
  front-end/with-the-developer/src/views/project/ProjectBoardView.vue
  front-end/with-the-developer/src/views/project/ProjectPostView.vue
  front-end/with-the-developer/src/views/team/TeamBoardView.vue
  front-end/with-the-developer/src/views/team/TeamPostView.vue
Labels: :new: feat

#347 [feat/mypage] #338 유효성 검사 완료, emit 처리 완료, 회원 수정 기능 완료
  README.md
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/mypage/info/ModifyUserInfo.vue
  front-end/with-the-developer/src/views/mypage/info/MypageInfo.vue
Labels: :new: feat

#352 [feat/login] feat: 정지 및 비활성화 된 회원은 로그인 불가능
  back-end/with-the-developer-monolithic/src/main/java/com/developer/common/exception/ErrorCode.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/command/domain/repository/UserRepository.java
  front-end/with-the-developer/src/views/user/LoginView.vue
Labels: :new: feat, :1234: chore

#357 feat: #356 결제 취소 기능 구현
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/OrderDetail.vue
Labels: :new: feat

#360 feat: #359 로그인시 게시판 메인페이지로 이동, 로그인 상태시 로고 누를 때 게시판 메인페이지로 이동
  front-end/with-the-developer/src/components/NavigationBar.vue
  front-end/with-the-developer/src/router/UserRouter.js
  front-end/with-the-developer/src/views/user/FindIdView.vue
  front-end/with-the-developer/src/views/user/LoginView.vue
  front-end/with-the-developer/src/views/user/ReSettingPwPage.vue
Labels: :new: feat

#362 fix: #361 굿즈 목록 페이징바 증식 문제 해결
  front-end/with-the-developer/src/views/GoodsList.vue
Labels: :hammer_and_wrench: fix

#354 [chore] #353 메인페이지 수정
  front-end/with-the-developer/src/views/main/MainPageBefore.vue
Labels: :new: feat

#366 chore: #365 결제 완료시 orderStatus OK로 변경,
  back-end/with-the-developer-monolithic/src/main/java/com/developer/block/command/application/controller/BlockCommandController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/dbti/command/application/controller/DbtiCommandController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/dbti/query/controller/DbtiQueryController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/order/command/application/service/OrderCommandService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/order/command/domain/aggregate/Order.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/order/query/controller/OrderQueryController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/payment/command/application/controller/PaymentCommandController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/payment/command/application/service/PaymentCommandServiceImpl.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/payment/query/controller/PaymentQueryController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/report/command/service/ReportCommandService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/command/application/service/UserCommandService.java
  front-end/with-the-developer/src/views/OrderDetail.vue
Labels: :new: feat, :1234: chore

#364 [fix/goods-list] #361 굿즈 목록 조회 안되던 문제 해결
  front-end/with-the-developer/src/views/GoodsList.vue
Labels: :hammer_and_wrench: fix

#368 [feat/order] 주문 관련 기능 구현
  back-end/with-the-developer-monolithic/src/main/java/com/developer/order/command/domain/aggregate/Order.java
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/Cart.vue
  front-end/with-the-developer/src/views/PayComplete.vue
Labels: :new: feat, :recycle: refactor

#372 [Chore/front-kakao] feat: 카카오 로그인 화면 구현, 토큰 세션시간 기입, 새로고침 동반한 이동 주석처리 및 router로 변경
  front-end/with-the-developer/src/App.vue
  front-end/with-the-developer/src/components/NavigationBar.vue
  front-end/with-the-developer/src/store/store.js
  front-end/with-the-developer/src/views/user/LoginView.vue
Labels: :new: feat, :1234: chore

#375 [feat/orders/design] 주문 내역 리스트 및 상세 조회 디자인
  back-end/with-the-developer-monolithic/src/main/java/com/developer/admin/command/service/AdminCommandService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/order/query/service/OrderQueryService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/report/command/service/ProjPostReportHandler.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/report/command/service/RecruitReportHandler.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/report/command/service/TeamPostReportHandler.java
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/OrderDetail.vue
  front-end/with-the-developer/src/views/OrderList.vue
Labels: :new: feat, :hammer_and_wrench: fix, :recycle: refactor

#376 [chore] 중복 import 삭제
  front-end/with-the-developer/src/router/index.js
Labels: :1234: chore

#380 [feat/kakao-login] feat: #378 카카오로그인 백엔드, 프론트 적용 및 로그인, 네비바 주석 처리 되어있는 Window.href 제거
  back-end/with-the-developer-monolithic/build.gradle
  back-end/with-the-developer-monolithic/src/main/java/com/developer/config/BeanConfig.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/command/domain/aggregate/User.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/oauth/kakao/OauthKakaoController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/oauth/kakao/OauthKakaoService.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/oauth/kakao/dto/KakaoTokenDTO.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/user/oauth/kakao/dto/KakaoUserDTO.java
  back-end/with-the-developer-monolithic/src/main/resources/application.yml
  front-end/with-the-developer/src/components/NavigationBar.vue
  front-end/with-the-developer/src/router/UserRouter.js
  front-end/with-the-developer/src/views/main/MainPageBefore.vue
  front-end/with-the-developer/src/views/user/KakaoLoginCompView.vue
  front-end/with-the-developer/src/views/user/LoginView.vue
Labels: :new: feat, :1234: chore

#382 [feat/search] #379 #381 통합 검색 기능 및 장바구니에 체크된 상품 없을 시 버튼 비활성화
  back-end/with-the-developer-monolithic/src/main/java/com/developer/search/query/controller/SearchController.java
  back-end/with-the-developer-monolithic/src/main/java/com/developer/search/query/dto/SearchIntegratedResultDTO.java
  back-end/with-the-developer-monolithic/src/main/resources/mappers/search/SearchMapper.xml
  front-end/with-the-developer/src/views/Cart.vue
  front-end/with-the-developer/src/views/OrderList.vue
  front-end/with-the-developer/src/views/SearchResults.vue
Labels: :new: feat

#383 [style/post] 모달창 css 수정
  front-end/with-the-developer/src/views/community/CommunityPostView.vue
  front-end/with-the-developer/src/views/project/ProjectPostView.vue
  front-end/with-the-developer/src/views/recruit/RecruitPostView.vue
  front-end/with-the-developer/src/views/team/TeamPostView.vue
Labels: :rainbow_flag: style, :recycle: refactor

#385 [chore/admin goods] 관리자 굿즈 충돌 해결중
  front-end/with-the-developer/src/views/admin/Admin-GoodsRegister.vue
  front-end/with-the-developer/src/views/admin/Admin-Tag.vue
  front-end/with-the-developer/src/views/admin/AdminGoods.vue
  front-end/with-the-developer/src/views/admin/AdminGoodsDetail.vue
Labels: :hammer_and_wrench: fix, :1234: chore

#386 [refactor] 관리자 권한일 경우 게시글 삭제 허용
  front-end/with-the-developer/src/views/community/CommunityPostView.vue
  front-end/with-the-developer/src/views/project/ProjectPostView.vue
  front-end/with-the-developer/src/views/team/TeamPostView.vue
Labels: :recycle: refactor

#387 [refactor] 서치바 삭제
  front-end/with-the-developer/src/views/community/CommunityBoardView.vue
  front-end/with-the-developer/src/views/project/ProjectBoardView.vue
  front-end/with-the-developer/src/views/recruit/RecruitBoardView.vue
  front-end/with-the-developer/src/views/team/TeamBoardView.vue
Labels: :recycle: refactor

#390 [Chore] #389 axios 호출 수정.
  front-end/with-the-developer/src/views/admin/post/AdminComuPost.vue
  front-end/with-the-developer/src/views/admin/post/AdminProjectPost.vue
  front-end/with-the-developer/src/views/admin/post/AdminRecruitPost.vue
  front-end/with-the-developer/src/views/admin/post/AdminTeamPost.vue
  front-end/with-the-developer/src/views/mypage/info/ModifyUserInfo.vue
  front-end/with-the-developer/src/views/mypage/info/MypageInfo.vue
  front-end/with-the-developer/src/views/mypage/msg/MypageBlock.vue
  front-end/with-the-developer/src/views/mypage/msg/MypageReadMsg.vue
  front-end/with-the-developer/src/views/mypage/msg/MypageReqMsg.vue
  front-end/with-the-developer/src/views/mypage/msg/MypageReqMsgDetail.vue
  front-end/with-the-developer/src/views/mypage/msg/MypageResMsg.vue
  front-end/with-the-developer/src/views/mypage/msg/MypageResMsgDetail.vue
Labels: :1234: chore

#391 Chore/admin order #388 관리자 주문 임시데이터, 관리자 굿즈 테스트위한 토큰 제거
  front-end/with-the-developer/src/components/AdminSideBar.vue
  front-end/with-the-developer/src/router/index.js
  front-end/with-the-developer/src/views/admin/Admin-GoodsRegister.vue
  front-end/with-the-developer/src/views/admin/AdminGoods.vue
  front-end/with-the-developer/src/views/admin/AdminGoodsDetail.vue
  front-end/with-the-developer/src/views/admin/AdminOrder.vue
Labels: :m: test, :hammer_and_wrench: fix, :1234: chore
